name: Test Action

on:
  push:
    branches: [  ]
  pull_request:
    branches: [  ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test-job:
    runs-on: ubuntu-latest

    env:
      GITHUB_CONTEXT: ${{ toJSON(github) }}
      COVERITY_PROJECT: test-action
      IS_PR: ${{ github.event_name == 'pull_request' }}
      IS_PUSH: ${{ github.event_name == 'push' }}

    steps:
    - name: On Push
      if: $IS_PUSH
      run: |
        set -x
        echo Stream is $STREAM
      env:
        STREAM: $COVERITY_PROJECT-${GITHUB_REF##*/}

    - name: On PR
      if: $IS_PR
      run: |
        set -x
        echo Stream is $STREAM
      env:
        STREAM: $COVERITY_PROJECT-$GITHUB_BASE_REF


    - name: Print environment
      run: |
        set -x
        export

# Forcing build 2021-04-30 3:21 p.m.